


###
GET http://localhost:6060/api/users

###
GET http://localhost:6060/api/users/2



###
POST http://localhost:6060/api/users
Content-Type: application/json

    {
        "details": {
            "firstName": "Amraaaa",
            "lastName": "Munkh",
            "email": "ami@gmail.com",
            "address": "Iveel hothon",
            "phoneNumber": "70118818",
            "gen": "male"
        },
        "signIn": {
            "userName": "Amaraa",
            "password": "huurhun huuhduud"
        },
        "admin": true,
        "order": [],
        "favItem": []
    }
###

DELETE http://localhost:6060/api/users/2

###
PUT http://localhost:6060/api/users/aa51a6b5-5080-4a33-9e30-ab247ffbbcdb
Content-Type: application/json

{
        "details": {
            "firstName": "AmraHuu",
            "lastName": "MunkhOchir",
            "email": "ami@gmail.com",
            "address": "Iveel hothon",
            "phoneNumber": "70118818"
        },
        "signIn": {
            "userName": "Amaraa",
            "password": "huurhun amra"
        },
        "admin": false,
        "order": [],
        "favItem": []
}

###
POST http://localhost:6060/api/users/login
Content-Type: application/json

{
     "signIn": {
        "userName": "Amaraa",
        "password": "huuurhun amra"
      }
}