


###
GET http://localhost:6060/api/users

###
GET http://localhost:6060/api/users/2



###
POST http://localhost:6060/api/users
Content-Type: application/json

    {
        "details": {
            "firstName": "Amraaaa",
            "lastName": "Munkh",
            "email": "ami@gmail.com",
            "address": "Iveel hothon",
            "phoneNumber": "70118818",
            "gen": "male"
        },
        "signIn": {
            "userName": "Amaraa",
            "password": "huurhun huuhduud"
        },
        "admin": true,
        "order": [],
        "favItem": []
    }
###

DELETE http://localhost:6060/api/users/2

###
PUT http://localhost:6060/api/users/aa51a6b5-5080-4a33-9e30-ab247ffbbcdb
Content-Type: application/json

{
        "details": {
            "firstName": "AmraHuu",
            "lastName": "MunkhOchir",
            "email": "ami@gmail.com",
            "address": "Iveel hothon",
            "phoneNumber": "70118818"
        },
        "signIn": {
            "userName": "Amaraa",
            "password": "huurhun amra"
        },
        "admin": false,
        "order": [],
        "favItem": []
}

###
POST http://localhost:6060/api/users/login
Content-Type: application/json

{
     "signIn": {
        "userName": "Amaraa",
        "password": "huuurhun amra"
      }
}


///////// 



###
GET http://localhost:6060/api/users?limit=5

###
GET http://localhost:6060/api/users/1


###
 POST http://localhost:6060/api/users
Content-Type: application/json

{
    "user_name": "bataa",
    "first_name": "boldoo",
    "last_name": "bataa",
    "user_pass": "1234Abc",
    "gender": "M",
    "address": "bzd 15-khoroo",
    "birth_date": "1999-12-31T16:00:00.000Z",
    "user_img": "dasddsa",
    "is_admin": false
}

### 
DELETE http://localhost:6060/api/users/8

###
PUT http://localhost:6060/api/users/9
Content-Type: application/json

{
      "user_name": "galbadrah",
      "first_name": "tsetsegsuren",
      "last_name": "tumurbaatar"
}